name: explore Debugging

on:
  push:  
  workflow_dispatch: 

env:
    user_1: naveen
    user_2: krishna    

jobs:
    debug:
     runs-on: ubuntu-latest
     steps:
     - name: debugging job
       run: echo "USERNAME=${{env.user_1}}" >> $GITHUB_ENV

     - name: printing value
       run: |
        echo $USERNAME  
        exit 1 

